### ISSUE TITLE
Unclear dependencies

### ISSUE THREAD

**Issue by florian-huber** [phpuech/OT_Analysis#3]
On top of the readme two shield.io stickers name PyQt and Python versions, but they seem unrelated to the rest of the software. In the setup.cfg it says python>=3.7 and no specification for PyQt.

**Comment by glyg** [comment]
Hi, I'm sorry for the long time it took to address this (by removing three lines in the README :/) commit 3bbd8bf closes this,
the dependencies are correctly specified in `setup.cfg`, I removed the stickers
